CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:provider.stage}-user-pool-client
    SupportedIdentityProviders: ["COGNITO"]
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthFlows: ["code", "implicit"]
    CallbackURLs: ["https://www.mimoo.dev/"]
    DefaultRedirectURI: "https://www.mimoo.dev/"
    AllowedOAuthScopes:
      ["email", "openid", "profile", "aws.cognito.signin.user.admin"]
    GenerateSecret: false
    UserPoolId:
      Ref: CognitoUserPool
